### ISSUE TITLE
Help elderly me

### ISSUE THREAD

**Issue by yarikoptic** [afni/afni_ci_test_data#8]
Hi @afni-rickr -- do you have notes from those few sessions we did a few months back... I feel user ran into an issue which we had (some binary files were committed to git instead of git-annex) and I can't recall it.

Related -- do you guys have some slack or whatever for rapid correspondence?

**Comment by afni-rickr** [comment]
Hi @yarikoptic  - email is generally our "rapid" correspondence method.  :)

I have some notes that could be mailed somewhere (will look for an address), though the commands went by quickly and my notes are light.  But my recollection is that a problem was due to a small bug in datalad (that you opened an issue on), where it was using the parent's annex rules, rather than the rules directly for the sub-module in question.
After some git unannex testing and rolling back in git, it seemed like doing separate publish steps was the way to go, as in step 5.
```
datalad publish --transfer-data=all --to=origin
datalad publish --transfer-data=all --to=afni_ci_test_data
```

**Comment by yarikoptic** [comment]
Thank you @afni-rickr !
